export type Post = { id: string; name: string; avatar: string; major: string; time: string; category: string; text: string; image?: string; likes: number; liked?: boolean; saved?: boolean; comments: {name: string; text: string}[] };
export const portrait = (id: string) => `https://i.pravatar.cc/100?img=${id}`;
export const initialPosts: Post[] = [
 {id:'1',name:'Sophie Chen',avatar:'47',major:'Design · Junior',time:'24 min ago',category:'Campus life',text:'Petition to make studying on the quad count as touching grass 🌱\nThe weather is doing its thing today. Who’s out here?',image:'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1200&q=85',likes:124,comments:[{name:'Alex Morgan',text:'The best study spot on campus, hands down.'},{name:'Marcus Johnson',text:'On my way with an iced coffee ☕'}]},
 {id:'2',name:'Marcus Johnson',avatar:'12',major:'Computer Science · Sophomore',time:'48 min ago',category:'Study buddies',text:'Anyone else in their “I’ll start the assignment after one more song” era? 🎧\nAnyway… CS 201 study session at the library, 7pm. Bring your laptop and your emotional support coffee.',likes:86,comments:[{name:'Sophie Chen',text:'The emotional support coffee is essential.'}]},
 {id:'3',name:'Emma Wilson',avatar:'44',major:'Business · Senior',time:'1 hr ago',category:'Looking for',text:'Looking for a fourth roommate for next semester! A sunny apartment, a very good coffee machine, and three very average cooks. Message me if you’re interested 🏡',likes:32,comments:[]},
 {id:'4',name:'Daniel Park',avatar:'13',major:'Music · Junior',time:'2 hr ago',category:'Campus life',text:'Our little band is playing at the student union Friday night! Come for the music, stay for the free pizza. Everyone’s welcome 🍕🎸',likes:57,comments:[]}
];
export const loops = [{name:'Study buddies',icon:'📚',members:'1.2k',color:'lavender',description:'Find your people for the next all-nighter.'},{name:'Campus life',icon:'🌱',members:'2.8k',color:'sage',description:'The little things that make campus feel like home.'},{name:'Food & coffee',icon:'☕',members:'846',color:'peach',description:'Good bites, great coffee, better company.'},{name:'Looking for',icon:'🔎',members:'624',color:'blue',description:'Roommates, recommendations, and everything between.'},{name:'Music & arts',icon:'🎨',members:'932',color:'pink',description:'Make something. Share something. Get inspired.'}];
export const events = [{id:'e1',day:'18',month:'SEP',name:'Sunset on the quad',detail:'Fri, 5:30 PM · Main Quad',icon:'🌅',color:'peach',description:'Grab a blanket and join your campus crew for acoustic music, lawn games, and a golden-hour hangout.'},{id:'e2',day:'20',month:'SEP',name:'Coffee & connections',detail:'Sun, 10:00 AM · The Daily Grind',icon:'☕',color:'sage',description:'Meet someone new over a good cup of coffee. Come solo or bring a friend — there’s a seat for everyone.'},{id:'e3',day:'22',month:'SEP',name:'Open mic night',detail:'Tue, 7:00 PM · Student Union',icon:'🎤',color:'lavender',description:'Music, poetry, comedy, and a very supportive crowd. Sign up at the door or just come cheer people on.'}];

export const interests = ['Outdoors', 'Arts & music', 'Food & coffee', 'Technology', 'Volunteering'];
export const clubs = [
 {id:'outdoors',name:'Oakridge Outdoors',icon:'🏕️',interest:'Outdoors',members:128,location:'Campus · Recreation Center',meeting:'Saturdays, 9 AM',description:'Easy hikes, weekend adventures, and new friends. Beginners always welcome.',event:'e1'},
 {id:'coffee',name:'Coffee & Conversation',icon:'☕',interest:'Food & coffee',members:86,location:'Nearby · The Daily Grind',meeting:'Saturdays, 10 AM',description:'Explore local cafés and meet students over your favorite cup. Come on your own — we’ll save you a seat.',event:'e2'},
 {id:'arts',name:'The Creative Collective',icon:'🎨',interest:'Arts & music',members:152,location:'Campus · Student Union',meeting:'Mondays, 7 PM',description:'Open mics, sketch nights, and people who love making things. All skill levels welcome.',event:'e3'},
 {id:'tech',name:'Build Together',icon:'💻',interest:'Technology',members:94,location:'Campus · Innovation Lab',meeting:'Wednesdays, 6 PM',description:'Find a project partner, try a new skill, or build your first app with a supportive student community.'},
 {id:'volunteer',name:'Oakridge Gives Back',icon:'🤝',interest:'Volunteering',members:73,location:'Nearby · Community Center',meeting:'Saturdays, 11 AM',description:'Meet caring people while helping local neighbors through food drives and community projects.'}
];
export const students = [
 {name:'Sophie Chen',avatar:'47',major:'Design · Junior',interests:['Arts & music','Food & coffee'],bio:'Always up for a sketch night or finding a new café.'},
 {name:'Marcus Johnson',avatar:'12',major:'Computer Science · Sophomore',interests:['Technology','Outdoors'],bio:'Building side projects and getting outside on weekends.'},
 {name:'Emma Wilson',avatar:'44',major:'Business · Senior',interests:['Volunteering','Food & coffee'],bio:'Looking for good coffee and ways to give back.'},
 {name:'Daniel Park',avatar:'13',major:'Music · Junior',interests:['Arts & music','Outdoors'],bio:'Let’s catch a local show or plan a weekend hike.'}
];
